### PR TITLE
update fpu code, bug fix in mem_mgr and valloc

### PR DESCRIPTION
**Pull request by ryuxin**
Tested with lfpu, lmicro_fpu, unit_cbuf and micro_cbuf

### CODE REVIEW

**Comment by gedare** [comment]
Looks good. I'm not sure why you use two different functions to set the ext_size in similar code in valloc_alloc() and valloc_alloc_at() though.

**Comment by ryuxin** [comment]
ext_size is used in different ways in valloc_alloc() and valloc_alloc_at(). You used it as the total size of memory in valloc_alloc_at(), but before it is used as the number of pages in valloc_alloc().
I can unify the usage in both functions.

**Comment by gedare** [comment]
I don't remember doing it that way for any good reason. Maybe it was more convenient to have it in bytes for me, for some reason, I don't know.

**Comment by gparmer** [comment]
In the future, please separate separate features into separate pulls (this is two features: fpu and a memory manager fix).  Sorry for the delay on this!

**Pull request merged**
