### PR TITLE
FreeRTOS stuff and micro_booter

### PR DESCRIPTION
**Pull request by hungry-foolish**
### Summary of this PR

The FreeRTOS and the micro_booter part of my modification.
Contains some block-commented original code for debug functionality comparison.

### Code Quality

As part of this pull request, I've considered the following:

Style:

- [x] Comments adhere to the Style Guide (SG)
- [x] Spacing adhere's to the SG 
- [x] Naming adhere's to the SG
- [x] All other aspects of the SG are adhered to, or exceptions are justified in this pull request

Code Craftsmanship:

- [x] I've made an attempt to remove all redundant code
- [x] I've considered ways in which my changes might impact existing code, and cleaned it up
- [x] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [x] I've commented appropriately where code is tricky
- [x] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### CODE REVIEW

**Comment by hungry-foolish** [comment]
@phanikishoreg @ryuxin

**Comment by phanikishoreg** [comment]
@hungry-foolish hey, this is too huge to review and I believe most of it is FreeRTOS code which doesn't need a review. Pointers in the commit description to the files/functions you changed from FreeRTOS or what you added will help in the review.

**Comment by gparmer** [comment]
@phanikishoreg is right.  I can't even find your changes.

Please do a separate PR with just your changes, and composite-specific stuff.  Keep this PR around so that we can refer to the broader code here.

**Comment by hungry-foolish** [comment]
Ok, I will list the functions that have changed

**Pull request closed without merging**
